### ISSUE TITLE
composes / compose-with for global CSS class names

### ISSUE THREAD

**Issue by danielweck** [css-modules/postcss-modules-scope#23]
The documentation gives this example ( https://github.com/css-modules/css-modules#composing-from-global-class-names ):
```
.otherClassName {
  composes: globalClassName from global;
}
```

...but the syntax supported by `postcss-modules-scope` is in fact:
```
.otherClassName {
  composes: global(globalClassName);
}
```

...as I discovered in the code:
https://github.com/css-modules/postcss-modules-scope/blob/fd4ffce8f1bba518336ceebb8449d8d6ca3a771d/src/index.js#L218

So, should this be documented somewhere?

Thanks for this piece of software though, keep up the good work! :)

**Comment by danielweck** [comment]
PS: I am using this handy "wrapper" https://github.com/sgtpep/csstag

**Comment by DiscreteBites** [comment]
Thanks for finding out! This has been bugging me for weeks. The documentation should really reflect this somewhere.

**Comment by alexander-akait** [comment]
Expected, because https://github.com/css-modules/postcss-modules-extract-imports/ converts `globalClassName from global` to `global(globalClassName)` for internal purposes
